# Project information
site_name: pressly/goose
site_url: https://pressly.github.io/goose/
site_description: >-
  The missing goose docs.

# Repository
repo_name: pressly/goose
repo_url: https://github.com/pressly/goose
edit_uri: ""

theme:
  name: material
  logo: assets/pressly.png
  palette:
    primary: white
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    # - navigation.indexes
    - navigation.top
    # - toc.integrate
    - content.code.annotate

plugins:
  - social

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - meta

nav:
  - Home:
      - Introduction: index.md
      - Getting started: getting-started.md
  - CLI Commands:
      - Supported: commands/supported.md
      - Experimental: commands/experimental.md
  - FAQ: FAQ.md
  - Blog:
      - Welcome: blog/welcome.md
      - Embedding migrations: blog/embed-sql-migrations.md
