# Project information
site_name: pressly/goose
site_url: https://pressly.github.io/goose/
site_description: >-
  The missing goose docs.

# Repository
repo_name: pressly/goose
repo_url: https://github.com/pressly/goose
edit_uri: ""

theme:
  name: material
  logo: assets/goose_logo.png
  palette:
    primary: white
    accent: light blue
  favicon: assets/goose_logo_cropped.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - content.code.annotate

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      post_url_date_format: YYYY
      post_readtime: false

  - search
  - social
  - tags
  - redirects:
      redirect_maps:
        getting-started.md: installation.md
        blog/welcome.md: blog/2021/welcome.md
        blog/embed-sql-migrations.md: blog/2021/embed-sql-migrations.md
        blog/better-tests.md: blog/2021/better-tests.md
        blog/out-of-order-migrations.md: blog/2021/out-of-order-migrations.md
        blog/no-version-migrations.md: blog/2021/no-version-migrations.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - meta
  - md_in_html
  - attr_list
  - def_list

extra_css:
  - stylesheets/extra.css

nav:
  - Getting Started:
      - Overview: index.md
      - Installation: installation.md
  - CLI Commands:
      - Supported: commands/supported.md
      - Experimental: commands/experimental.md
  - Blog:
      - blog/index.md
