# Project information
site_name: pressly/goose
site_url: https://pressly.github.io/goose/
site_description: >-
  The missing goose docs.

# Repository
repo_name: pressly/goose
repo_url: https://github.com/pressly/goose
edit_uri: ""

theme:
  name: material
  logo: assets/goose_logo.png
  palette:
    primary: white
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    # - navigation.indexes
    - navigation.top
    # - toc.integrate
    - content.code.annotate

plugins:
  - search
  - social
  - tags
  - redirects:
      redirect_maps:
        blog/welcome.md: blog/2021/welcome.md
        blog/embed-sql-migrations.md: blog/2021/embed-sql-migrations.md
        blog/better-tests.md: blog/2021/better-tests.md
        blog/out-of-order-migrations.md: blog/2021/out-of-order-migrations.md
        blog/no-version-migrations.md: blog/2021/no-version-migrations.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - meta
  - md_in_html
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
      - Introduction: index.md
      - Getting started: getting-started.md
  - CLI Commands:
      - Supported: commands/supported.md
      - Experimental: commands/experimental.md
  - FAQ: FAQ.md
  - Blog:
      - 2021:
          - blog/2021/welcome.md
          - blog/2021/embed-sql-migrations.md
          - blog/2021/better-tests.md
          - blog/2021/out-of-order-migrations.md
          - blog/2021/no-version-migrations.md
