name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install mkdocs-redirects
      - run: pip install git+https://${{ secrets.PAT_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs build --clean --config-file mkdocs.yml -d site -v
      - run:
          MKDOCS_VERSION=$(pip list --no-index --format=json | jq -r '.[] | select(.name=="mkdocs").version')
          MATERIAL_VERSION=$(pip list --no-index --format=json | jq -r '.[] | select(.name=="mkdocs-material").version')
          SHA_SHORT=$(git rev-parse --short HEAD)
          MESSAGE="Deployed ${SHA_SHORT} with MkDocs version - ${MKDOCS_VERSION} (${MATERIAL_VERSION})"
          echo "{MESSAGE}={MESSAGE}" >> $GITHUB_ENV
      - name: deploy docs upstream
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: site/
          destination-github-username: "pressly"
          destination-repository-name: "goose"
          user-email: mf192@icloud.com
          commit-message: ${{ env.MESSAGE }}
          target-branch: gh-pages
